groups:
  - name: DexAuthentication
    rules:
      - alert: DexAuthFailureRate
        expr: sum(rate(http_requests_total{job="dex", handler=~"/auth.*|/callback", code=~"4..|5.."}[5m])) / sum(rate(http_requests_total{job="dex", handler=~"/auth.*|/callback"}[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Dex has a high rate of failed authentication requests"
          description: "More than 10% of authentication requests are failing with HTTP error codes."

      - alert: DexHighLatency
        expr: histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{job="dex", handler=~"/auth.*|/callback"}[5m])) by (le, handler)) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Dex authentication latency is high"
          description: "95th percentile of request duration for {{ $labels.handler }} is {{ $value }} seconds."
