apiVersion: v2
name: gcp-iam-policy-members
description: A Helm chart that Creates GCP IAM Policy Memebers through Config Connector
type: application
version: 0.1.1
appVersion: "0.1.1"
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
