remote: origin
target-branch: main
chart-dirs:
  - charts

chart-repos:
 - external-secrets=https://charts.external-secrets.io
 - dex=https://charts.dexidp.io
 - ekp-helm=https://edixos.github.io/ekp-helm
 - argo-cd=https://argoproj.github.io/argo-helm
 - kyverno=https://kyverno.github.io/kyverno/
helm-extra-args: "--timeout 600s"
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
