remote: origin
target-branch: main
chart-dirs:
  - charts

chart-repos:
 - external-secrets=https://charts.external-secrets.io
 - dex=https://charts.dexidp.io
 - ekp-helm=https://edixos.github.io/ekp-helm
 - argo-cd=https://argoproj.github.io/argo-helm
 - kyverno=https://kyverno.github.io/kyverno/
 - cert-manager=https://charts.jetstack.io
 - kube-prometheus-stack=https://prometheus-community.github.io/helm-charts
 - velero=https://vmware-tanzu.github.io/helm-charts
 - oauth2-proxy=https://oauth2-proxy.github.io/manifests
helm-extra-args: "--timeout 600s"
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
