remote: origin
target-branch: main
chart-dirs:
  - charts

chart-repos:
 - external-secrets=https://charts.external-secrets.io
helm-extra-args: "--timeout 600s"
validate-chart-schema: false
chart-repos:
 - dex=https://charts.dexidp.io
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
