{{- range .Values.pushSecrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "1" | quote }}
spec:
{{ toYaml .spec | nindent 2 }}
{{- end }}
