apiVersion: v2
name: gcp-dns-zone
description: A Helm chart for gcp-dns-zone resource
type: application
version: 0.1.0
maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
