{{- range $name, $policy := .Values.backendTrafficPolicies }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $name }}
  namespace: {{ $policy.namespace | default $.Release.Namespace }}
  {{- if $policy.annotations }}
  annotations:
    {{- toYaml $policy.annotations | nindent 4 }}
  {{- end }}
  {{- if $policy.labels }}
  labels:
    {{- toYaml $policy.labels | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml $policy.spec | nindent 2 }}
---
{{- end }}