{{- range $name, $config := .Values.httpRoutes -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ $config.namespace }}
  labels:
    {{- include "envoy-gateway.labels" $ | nindent 4 }}
spec:
{{- if $config.hostnames }}
  hostnames:
{{ toYaml $config.hostnames | indent 4 }}
{{- end }}
  parentRefs:
{{ toYaml $config.parentRefs | indent 4 }}
  rules:
{{ toYaml $config.rules | indent 4 }}
---
{{ end -}}
