apiVersion: v2
name: velero
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "1.15.2"
dependencies:
  - name: velero
    version: 8.5.0
    repository: "https://vmware-tanzu.github.io/helm-charts"
  - name: gcp-workload-identity
    version: 0.1.1
    repository: "https://edixos.github.io/ekp-helm"
    alias: workloadIdentity
    tags:
      - configConnector
  - name: gcp-iam-policy-members
    version: 0.1.2
    repository: "https://edixos.github.io/ekp-helm"
    alias: iamPolicyMembers
    tags:
      - configConnector
  - name: gcp-iam-custom-role
    version: 0.1.0
    repository: "https://edixos.github.io/ekp-helm"
    alias: iamCustomRole
    tags:
      - configConnector
  - name: gcp-bucket
    version: 0.1.0
    repository: "https://edixos.github.io/ekp-helm"
    alias: gcpbucket
    tags:
      - configConnector

maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
