{{- if .Values.backups.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: infra-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.backups.schedule | quote }}
  template:
    hooks: {}
    includedNamespaces:
{{- range .Values.backups.namespaces }}
      - {{ . | quote }}
{{- end }}
    ttl: {{ .Values.backups.ttl | quote }}
{{- end }}
