# See https://github.com/helm/chart-testing#configuration
remote: origin
chart-dirs:
  - charts
helm-extra-args: --timeout=500
chart-repos:
 - dex=https://charts.dexidp.io
 - ekp-helm=https://edixos.github.io/ekp-helm
check-version-increment: true
