apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: kube-system
  labels:
    app.kubernetes.io/name: scaleway-csi
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SCW_ACCESS_KEY: '{{ print "{{ .SCW_ACCESS_KEY }}" }}'
        SCW_SECRET_KEY: '{{ print "{{ .SCW_SECRET_KEY }}" }}'
        SCW_DEFAULT_REGION: {{ .Values.region | quote }}
        SCW_DEFAULT_ZONE: {{ .Values.zone | quote }}
        SCW_DEFAULT_PROJECT_ID: {{ .Values.projectId | quote }}
  data:
    - secretKey: SCW_ACCESS_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: SCW_ACCESS_KEY
    - secretKey: SCW_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: SCW_SECRET_KEY