{{- if .Values.networkPolicyTemplate.enabled }}
apiVersion: networking.cloud.renault-digital.com/v1alpha1
kind: InfraNetworkPolicyTemplate
metadata:
  name: {{ printf "from-%s" (include "call-nested" (list . "ingressNginx" "ingress-nginx.name")) }}
  labels:
    app: {{ include "call-nested" (list . "ingressNginx" "ingress-nginx.name") }}
spec:
  description: "Template to create network policy ingress in order to receive traffic from nginx ingress controller"
  networkPolicy:
    policyType: "Ingress"
    podSelector: {}
    ingress:
      - from:
          - namespaceSelector:
{{- .Values.networkPolicyTemplate.namespaceSelectors | toYaml | nindent 14 }}
            podSelector:
              matchLabels:
                app.kubernetes.io/component: controller
                {{- include "call-nested" (list . "ingressNginx" "ingress-nginx.selectorLabels") | nindent 16 }}
{{- end }}