{{- if .Values.prometheus.enabled }}
{{- $root := . }}
{{- $files := .Files }}
{{ range $path, $bytes := .Files.Glob "resources/prometheus-rules/*.yaml" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ toYaml $.Values.prometheus.rules.labels | nindent 4 }}
    role: alert-rules
  name: {{ include "call-nested" (list $root "ingressNginx" "ingress-nginx.fullname") }}-{{ base $path | replace ".yaml" ".rules" }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
{{ with $root.Files.Get $path  }}
    {{- . | indent 2 }}
{{ end }}
{{ end }}
{{- end }}