{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ template "prometheus.roleBindingKind" . }}
metadata:
  name: {{ template "prometheus.fullname" . }}-prometheus
  labels:
    app: {{ template "prometheus.name" . }}-prometheus
    {{- include "prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ template "prometheus.roleKind" . }}
  name: {{ template "prometheus.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
