{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ template "prometheus.roleKind" . }}
metadata:
  name: {{ template "prometheus.fullname" . }}-prometheus
  labels:
    app: {{ template "prometheus.name" . }}-prometheus
    {{- include "prometheus.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
      - list
      - watch
  # This permission are not in the kube-prometheus repo
  # they're grabbed from https://github.com/prometheus/prometheus/blob/master/documentation/examples/rbac-setup.yml
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
{{- if not .Values.rbac.scopeNamespaced }}
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
{{- end }}
{{- end }}
