{{- if and .Values.oidc.enabled .Values.oidc.secret.create }}
apiVersion: "v1"
kind: Secret
metadata:
  name: {{ include "prometheus.oidc.secretName" . | quote }}
  labels:
    app: {{ template "prometheus.name" . }}-prometheus
    {{- include "prometheus.labels" . | nindent 4 }}
  {{- if .Values.oidc.secret.annotations }}
  annotations:
  {{- toYaml .Values.oidc.secret.annotations | nindent 4 }}
  {{- end }}
data:
  {{ .Values.oidc.secret.encryptionKeyKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{ .Values.oidc.secret.clientSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
