{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
{{- if .labels }}
  labels:
{{ toYaml .labels | indent 4 }}
{{- end }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
spec:
{{ toYaml .spec | indent 2 }}
{{- end }}