{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.eso.targetSecretName }}
  namespace: kube-system
  labels:
    {{- include "scaleway-ccm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.eso.clusterSecretStoreName }}
  target:
    name: {{ .Values.eso.targetSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SCW_ACCESS_KEY: '{{ "{{ .SCW_ACCESS_KEY }}" }}'
        SCW_SECRET_KEY: '{{ "{{ .SCW_SECRET_KEY }}" }}'
        SCW_DEFAULT_REGION: {{ .Values.scaleway.region | quote }}
        SCW_DEFAULT_PROJECT_ID: {{ .Values.scaleway.projectId | quote }}
        SCW_DEFAULT_ZONE: {{ .Values.scaleway.zone | quote }}
        SCW_CCM_PREFIX: {{ .Values.scaleway.clusterName | quote }}
        PN_ID: {{ .Values.scaleway.privateNetworkId | quote }}
  data:
  - secretKey: SCW_ACCESS_KEY
    remoteRef:
      key: {{ .Values.eso.sourceSecretName }}
      property: SCW_ACCESS_KEY
  - secretKey: SCW_SECRET_KEY
    remoteRef:
      key: {{ .Values.eso.sourceSecretName }}
      property: SCW_SECRET_KEY
{{- end }}
