apiVersion: v2
name: gcp-gke-cluster
description: A Helm chart to provision a GKE Cluster via Config Connector.
type: application
version: 0.1.3
appVersion: "0.1.3"
maintainers:
  - name: ilyasabdellaoui
    email: ilyas.abdellaoui21@gmail.com
    url: https://github.com/ilyasabdellaoui
dependencies:
- name: gcp-subnetwork
  version: "0.1.5"
  repository: "https://edixos.github.io/ekp-helm"
  alias: gcpSubnetwork
  tags:
    - networking
- name: gcp-vpc-network
  version: "0.1.3"
  repository: "https://edixos.github.io/ekp-helm"
  alias: gcpVpcNetwork
  tags:
    - networking
- name: gcp-bigquery-dataset
  version: 0.1.0
  repository: "https://edixos.github.io/ekp-helm"
  alias: bigquery-dataset
  condition: bigquery-dataset.enabled
- name: gcp-cloud-nat
  version: 0.1.0
  repository: "https://edixos.github.io/ekp-helm"
  alias: gcpCloudNat
  tags: 
  - enable-nat
