apiVersion: v2
name: longhorn
description: A Helm chart for Longhorn
type: application
version: 0.1.1
appVersion: "v1.11.2"
dependencies:
  - name: longhorn
    version: 1.11.2
    repository: "https://charts.longhorn.io"
    alias: longhorn
