---
apiVersion: v2
name: longhorn-wrapper
description: A Helm wrapper chart for Longhorn and associated resources
type: application
version: 0.1.0
appVersion: "1.6.0"
dependencies:
  - name: longhorn
    version: 1.6.0
    repository: "[https://charts.longhorn.io](https://charts.longhorn.io)"
    alias: longhorn