{{- if .Values.ingress.enabled -}}
{{- $root := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "grafana-stack.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "call-nested" (list . "grafana" "grafana.fullname") }}
            port:
              name: {{ .Values.grafana.service.portName }}
{{- end -}}
