apiVersion: v2
name: gcp-workload-identity
description: A Helm chart for workload identity
type: application
version: 0.1.1
appVersion: "1.16.0"
maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
