global:
  # -- Allows to deploy in another namespace than the release one
  # @default -- `nil`
  cnrmNamespace: ""
  # -- Google Project ID
  gcpProjectId: myprojectid
  # -- Keep the VPC even after the kcc resource deletion.
  abandon: false

# -- Name of the VPC Network.
name: "ekp-vpc"
# -- The display name for the VPC Network. Can be updated without creating a new resource.
displayName: "EKP VPC"
# -- A text description of the VPC Network. Must be less than or equal to 256 UTF-8 bytes.
description: "EKP VPC Network for infrastructure."

# -- Enable custom subnet creation. If false, the VPC Network will not create subnets.
autoCreateSubnetworks: false
# -- Keep the default routes on creation by default. If true, the VPC Network will delete the default routes.
deleteDefaultRoutesOnCreate: false
# -- Maximum Transmission Unit in bytes.
mtu: 1460
# -- Routing mode for the VPC Network.
routingMode: "REGIONAL"

# -- Additional values for documentation (not used in ComputeNetwork spec) or dependent charts (e.g. for creating subnets)
region: "europe-west1"
# -- Additional values for documentation (not used in ComputeNetwork spec) or dependent charts (e.g. for creating subnets)
cidr: "10.0.0.0/8"

# -- Add annotations to the VPC Network.
annotations: {}
