apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 0.1.4
appVersion: "1.17.1"
maintainers:
  - name: wiemaouadi
    email: wiem.aouadi3@gmail.com
    url: https://github.com/wiemaouadi
  - name: smileisak
    email: ikaboubi@gmail.com
    url: https://github.com/smileisak
dependencies:
  - name: cert-manager
    version: "v1.18.1"
    repository: "https://charts.jetstack.io"
    alias: certmanager
  - name: gcp-workload-identity
    version: 0.1.1
    repository: "https://edixos.github.io/ekp-helm"
    alias: workloadIdentity
    tags:
      - configConnector
  - name: gcp-iam-policy-members
    version: 0.1.2
    repository: "https://edixos.github.io/ekp-helm"
    alias: iamPolicyMembers
    tags:
      - configConnector
