{
 "title": "ExternalDns",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(external_dns_registry_endpoints_total, namespace)"
   },
   {
    "name": "http_path",
    "query": "label_values(http_request_duration_seconds, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "Http Request duration: $http_path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "repeat": "http_path",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "\n\nhttp_request_duration_seconds{path=\"$http_path\", job=\"external-dns\", namespace=\"$namespace\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Http Request duration: $http_path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "\n\nhttp_request_duration_seconds{path=\"$http_path\", job=\"external-dns\", namespace=\"$namespace\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Http Request duration: $http_path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "\n\nhttp_request_duration_seconds{path=\"$http_path\", job=\"external-dns\", namespace=\"$namespace\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Registry",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total{namespace=\"$namespace\"}",
     "legendFormat": "Endpoints in the registry"
    },
    {
     "expr": "registry_errors_total{namespace=\"$namespace\"}",
     "legendFormat": "Total errors"
    }
   ]
  },
  {
   "title": "Source",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total{namespace=\"$namespace\"}",
     "legendFormat": "Endpoints all sources"
    },
    {
     "expr": "source_errors_total{namespace=\"$namespace\"}",
     "legendFormat": "Total errors"
    }
   ]
  }
 ]
}