{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecrets[].name is required" .name }}
  {{- with .namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "victoria-metrics-k8s-stack.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | default "0" | quote }}
    {{- if ($.Values.global).enableArgocdAnnotations }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
