{{- range .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
{{ toYaml .spec | nindent 2 }}
{{- end }}
