name: Auto Bump Helm Dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - feat/ekp-renovate
permissions:
  contents: write
  pull-requests: write

jobs:
  bump-helm-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install yq & jq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          sudo apt-get update && sudo apt-get install -y jq

      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="1.14.2"
          curl -L "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz" | tar -xz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/helm-docs

      - name: Add our Helm repo
        run: |
          helm repo add ekp-helm https://edixos.github.io/ekp-helm
          helm repo update

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver ruamel.yaml yamllint

      - name: Run bump-dependencies script
        id: bump-dependencies
        run: |
          python scripts/bump_dependencies.py
        env:
          DRY_RUN: "false"
          SKIP_PR: "true"
          UPDATE_VALUES: "true"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Create Pull Request using GitHub CLI
        if: steps.bump-dependencies.outputs.updated == 'true'
        run: |
          BRANCH="${{ steps.bump-dependencies.outputs.branch }}"
          PR_TITLE="chore(deps-bump): auto bumped helm dependencies"
          PR_BODY="## Automated Helm Chart Dependency Updates

          This PR was automatically generated to update Helm chart dependencies to their latest versions.

          ### Summary of Changes
          - Updated dependencies in charts with available updates
          - Bumped chart patch versions
          - Updated default values from upstream charts
          - Regenerated documentation

          Auto-generated by the [Auto Bump Helm Dependencies](.github/workflows/auto-bump-helm-deps.yml) workflow."

          # Store token in a variable but unset from environment
          TOKEN="${GITHUB_TOKEN}"
          unset GITHUB_TOKEN
          
          # Authenticate and create PR
          echo "$TOKEN" | gh auth login --with-token
          PR_URL=$(gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head "$BRANCH")
          echo "Created PR: $PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}