name: Auto Bump Helm Dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - feat/ekp-renovate
permissions:
  contents: write
  pull-requests: write

jobs:
  bump-helm-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install yq & jq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          sudo apt-get update && sudo apt-get install -y jq

      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="1.14.2"
          curl -L "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz" | tar -xz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/helm-docs

      - name: Add our Helm repo
        run: |
          helm repo add ekp-helm https://edixos.github.io/ekp-helm
          helm repo update

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver ruamel.yaml yamllint

      - name: Run bump-dependencies script
        id: bump-dependencies
        run: |
          python scripts/bump_dependencies.py
        env:
          DRY_RUN: "false"
          SKIP_PR: "true"
          UPDATE_VALUES: "true"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps-bump): auto bumped helm dependencies"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ${{ steps.bump-dependencies.outputs.branch }}
          base: main
          delete-branch: true
          title: "chore(deps-bump): auto bumped helm dependencies"
          body: |
            ## Automated Helm Chart Dependency Updates

            This PR was automatically generated to update Helm chart dependencies to their latest versions.

            ### Summary of Changes
            - Updated dependencies in charts with available updates
            - Bumped chart patch versions
            - Updated default values from upstream charts
            - Regenerated documentation

            Auto-generated by the [Auto Bump Helm Dependencies](.github/workflows/auto-bump-helm-deps.yml) workflow.
