name: Auto Bump Helm Dependencies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no changes)'
        type: boolean
        default: false
      skip_pr:
        description: 'Skip PR creation'
        type: boolean
        default: true
      update_values:
        description: 'Update values.yaml files'
        type: boolean
        default: true
  push:
    branches:
      - feat/ekp-renovate
permissions:
  contents: write
  pull-requests: write

jobs:
  bump-helm-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="1.14.2"
          curl -L "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz" | tar -xz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/helm-docs

      - name: Add our Helm repo
        run: |
          helm repo add ekp-helm https://edixos.github.io/ekp-helm
          helm repo update

      - name: Set branch name variable with date
        id: vars
        run: echo "BRANCH_NAME=chore/bump-helm-deps-$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      # - name: Run bump-dependencies script
      #   id: bump-dependencies
      #   run: |
      #     bash scripts/bump-dependencies.sh
      #   env:
      #     DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
      #     SKIP_PR: "true"
      #     UPDATE_VALUES: ${{ github.event.inputs.update_values || 'true' }}
      #     SKIP_PUSH: "true"
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH_NAME: ${{ steps.vars.outputs.BRANCH_NAME }}
      #     VERBOSE: "true"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semver ruamel.yaml yamllint

      - name: Run bump-dependencies script
        id: bump-dependencies
        run: |
          python scripts/bump_dependencies.py
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
          SKIP_PR: "true"
          UPDATE_VALUES: ${{ github.event.inputs.update_values || 'true' }}
          BRANCH_NAME: ${{ steps.vars.outputs.BRANCH_NAME }}

      # - name: Create Pull Request
      #   if: ${{ steps.bump-dependencies.outputs.updated == 'true' && github.event.inputs.skip_pr != 'true' && github.event.inputs.dry_run != 'true' }}
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     commit-message: >-
      #       ${{ steps.bump-dependencies.outputs.commit_message || format('chore: bump helm dependencies ({0})', github.run_id) }}
      #     committer: "GitHub Actions <actions@github.com>"
      #     branch: ${{ steps.vars.outputs.BRANCH_NAME }}
      #     delete-branch: true
      #     title: >-
      #       ${{ steps.bump-dependencies.outputs.commit_message || format('chore: bump Helm dependencies ({0})', github.run_id) }}
      #     body-path: /tmp/helm_changelog.md
      #     base: main

      # - name: PR Creation Success
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   run: |
      #     echo "✅ Pull Request #${{ steps.cpr.outputs.pull-request-number }} created successfully!"
      #     echo "🔗 URL: ${{ steps.cpr.outputs.pull-request-url }}"
