{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{- include "configconnector-operator.commonAnnotations" . | nindent 4 }}
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: {{ include "configconnector-operator.fullname" .}}-cnrm-viewer-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configconnector-operator.fullname" .}}-cnrm-viewer
subjects:
  - kind: ServiceAccount
    name: {{ include "configconnector-operator.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{- include "configconnector-operator.commonAnnotations" . | nindent 4 }}
  labels:
    cnrm.cloud.google.com/operator-system: "true"
  name: {{ include "configconnector-operator.fullname" .}}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configconnector-operator.fullname" .}}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "configconnector-operator.serviceAccountName" .}}
    namespace: {{ .Release.Namespace }}
{{- end }}