{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "configconnector-operator.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "configconnector-operator.labels" . | nindent 4 }}
  name: {{ include "configconnector-operator.serviceAccountName" .}}
  namespace: {{ .Release.Namespace }}
{{- end }}